### ISSUE TITLE
Unterstützer des CoderDojos auf der Webseite aufführen

### ISSUE THREAD

**Issue by mk1012** [coderdojoka/coderdojoka.github.io#11]
Wir sollten auf der Webseite, dass KIT und jetzt auch inovex als Unterstützer des CoderDojos aufführen? Ich hatte gedacht so ganz unten in der Fußzeile
(Ich frage bei inovex aber noch mal nach, ob Sie das wünschen und wenn ja ob se ein kleines Logo haben).
Des verleiht uns mehr Glaubwürdigkeit unds KIT freut sich doch immer über Erwähnungen :)

**Comment by tpambor** [comment]
Ich hab nichts dagegen. Ich hätte vorgeschlagen neuer Abschnitt "Unterstützer" nach "Wo finden die Treffen statt" und der Karte mit Logo und Link.

**Comment by mk1012** [comment]
Ja, da hatte ich auch gedach Fußzeile war ein bisschen falsch

**Comment by mk1012** [comment]
wir haben übringens jetzt auch von inovex die Antwort bekommen, dass wir sie gerne featuren dürfen:

"Über eine Logo-Platzierung würden wir uns natürlich freuen, die Datei findest du im Anhang als png und Vektorgrafik. Wenn daneben ein Text erscheint, hier unsere standardisierte Zusammenfassung. Wenn nicht genügt natürlich auch das Logo: 

inovex ist ein IT-Projekthaus mit dem Schwerpunkt „Digitale Transformation“. Über 170 Berater und IT-Ingenieure unterstützen Unternehmen bei der Digitalisierung ihres Kerngeschäfts und bei der Realisierung von neuen Wertschöpfungsmodellen.
Zum Portfolio von inovex gehören Digital Consulting, Web und Mobile Development, Business Intelligence, Big Data und Search, Data Center Automation und Cloud-Infrastrukturen sowie Trainings und Coachings.
inovex ist in Karlsruhe, Pforzheim, München, Köln und Hamburg (ab Sommer 2015) ansässig und bundesweit in Projekte involviert."

![inovex-logo-ohne-rahmen-transparent](https://cloud.githubusercontent.com/assets/7687290/8762117/bbc18768-2d6f-11e5-94c5-262ab1d4696a.png)
