### ISSUE TITLE
PDF Build der Satzung nicht mehr erreichbar

### ISSUE THREAD

**Issue by sunarch** [coderdojoka/coderdojoka.github.io#22]
ShareLaTeX Cloud Compiler existiert seit dem 21. Juli nicht mehr, daher führt der Link der Satzung im PDF-Format ([https://www.sharelatex.com/github/repos/coderdojoka/satzung-hochschulgruppe/builds/latest/output.pdf](https://www.sharelatex.com/github/repos/coderdojoka/satzung-hochschulgruppe/builds/latest/output.pdf)) auf der Webseite auf folgenden Bericht:

[https://www.sharelatex.com/learn/Kb%2FWhere%20is%20Github%20CI](https://www.sharelatex.com/learn/Kb%2FWhere%20is%20Github%20CI)

GitHub Sync funktioniert theoretisch noch, es sollte also nur der Build zurückkopiert werden in die Satzung-Repo. Dann kann von der Webseite auf die Datei verlinkt werden.

**Comment by mk1012** [comment]
Ich hab einfach das PDF mal hochgestellt, siehe: https://github.com/coderdojoka/satzung-hochschulgruppe/pull/1

**Comment by sunarch** [comment]
@mk1012 Von dem anderen Repo kann das PDF nur zum Herunterladen gelinkt werden, nicht zum Anzeigen im Browser. Für Anzeigen muss das PDF in einem GitHub Pages Repo sein (also in diesem). Ist es gut, wenn nur das Herunterladen möglich ist, oder soll ich das PDF in diesen Repo kopieren?

**Comment by mk1012** [comment]
Hmm.. die Frage ist, wer sich die Satzung überhaupt anschauen will.. Prinzipiell ist mir das egal. Runterladen reicht doch vollkommen?

**Comment by sunarch** [comment]
Ich finde es mehr zugänglich, wenn man das auch online anschauen kann. Ich zumindest bevorzuge so eine Option zu haben, aber letztendlich ist es nicht so wichtig. Sag wie du es haben willst, und ich mache es so.

**Comment by mk1012** [comment]
Ok, wenn du meinst es ist eine gute Idee, können wir das gerne machen.
