### ISSUE TITLE
Navigationszeile/Header schlecht lesbar im Anfangszustand

### ISSUE THREAD

**Issue by blipp** [coderdojoka/coderdojoka.github.io#4]
Mit dem neuen dunklen Design ist die Navigation schlecht lesbar, wenn die Website ganz nach oben gescrollt ist, siehe Screenshots. Möglicherweise könnte das durch das Einfügen eines Hintergrunds auch im Anfangszustand gelöst werden. Sobald man nach unten scrollt, wird ja ein Hintergrund eingeblendet und die Navigation ist lesbar. Im Anfangszustand gehen die Links meiner Meinung nach zu sehr unter, mit den Codezeilen im Hintergrund.

![Firefox, unter Linux](https://cloud.githubusercontent.com/assets/138279/7078773/adb514e2-df1c-11e4-87cc-998dd2625c1c.png)

![Chrome, unter Linux](https://cloud.githubusercontent.com/assets/138279/7078776/b2793828-df1c-11e4-9c4a-f7cb5f5d1fcb.png)

**Comment by tpambor** [comment]
Ich kümmer mich darum.
Kann mir das nicht zuweisen, dazu müsste ich wahrscheinlich in der Organisation sein.

**Comment by tpambor** [comment]
Mein Änderungsvorschlag ist in #5 zu finden.
Eine Vorschau gibt es unter: http://wiizzard.github.io/coderdojoka.github.io/

**Comment by mk1012** [comment]
Cool, Wieder lesbar.
