### ISSUE TITLE
Adresse der Hochschulgruppe bei Kontakt dazuschreiben

### ISSUE THREAD

**Issue by blipp** [coderdojoka/coderdojoka.github.io#9]
Dann erfüllen wir auch etwaige Forderungen nach einem Impressum:

CoderDojo Karlsruhe
c/o AStA KIT
Adenauerring 7
76131 Karlsruhe

Vorher mal im AStA-Thekenraum gucken, ob wir wirklich schon ein Postfach haben…

**Comment by tpambor** [comment]
Erledigt mit c551dabd51c8c4e77eb1b2d46c3136e5cd02793c
